/*
 *   
 *   Highly divisible triangular number
 *   
 *   Problem 12
 *   
 *      Published on Friday, 8th March 2002, 06:00 pm; Solved by 112616
 *   
 *      The sequence of triangle numbers is generated by adding the natural
 *      numbers. So the 7^th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7
 *      = 28. The first ten terms would be:
 *   
 *      1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *   
 *      Let us list the factors of the first seven triangle numbers:
 *   
 *         1: 1
 *         3: 1,3
 *         6: 1,2,3,6
 *        10: 1,2,5,10
 *        15: 1,3,5,15
 *        21: 1,3,7,21
 *        28: 1,2,4,7,14,28
 *   
 *      We can see that 28 is the first triangle number to have over five
 *      divisors.
 *   
 *      What is the value of the first triangle number to have over five
 *      hundred divisors?
 *   
*/

#include <stdio.h>
#include <math.h>
#include <limits.h>

int countFactors(int num);

int main()
{
	int test = 3;
	int i = 1;
	while (i < INT_MAX) {
		test = test + i; /* Ugh, how do you do this? */
		if (countFactors(test) > 5) {
			printf("The first triangle number to have over 500 divisors is %d.\n", test);
			return 0;
		}
	}
	return 0;
}

int countFactors(int num)
{
	int count = 0;
	int i;
	for (i = 1; i <= sqrt(num); i++) {
		if (num % i == 0)
			count++;
	} 
	return count * 2; /* There's a factor on the other side of the square as well */
}
